### ISSUE TITLE
Composer.json should contain dependency on knplabs/knp-menu-bundle

### ISSUE THREAD

**Issue by 7ochem** [zicht/menu-bundle#28]
knplabs/knp-menu-bundle is being used, so composer.json should reflect that. Now, this bundle works coincidentally, because it is being used in projects which also use Sonata Admin, which has a dependency on knplabs/knp-menu-bundle.

https://github.com/zicht/menu-bundle/search?q=Knp&type=code

**Comment by erik-zicht** [comment]
Fixed in https://github.com/zicht/menu-bundle/blob/release/4.x/composer.json#L14
