### ISSUE TITLE
performance optimisations

### ISSUE THREAD

**Issue by muhammedeminakbulut** [zicht/menu-bundle#7]
Most of the doctrine entities and queries does lack the availibility of good indices and cached queries.

**Comment by muhammedeminakbulut** [comment]
example missing indexes for query  `SELECT id, name, language, lft, rgt FROM menu_item WHERE lvl=0 AND (language IS NULL OR language='nl')
Parameters: []` and its missing parameters so concatenation is used instead of parameters.

**Comment by erik-zicht** [comment]
Indexes are added throughout and work as they should
